### ISSUE TITLE
Summarise data in Excel Sheet

### ISSUE THREAD

**Issue by lug-robin** [YuriDevAT/accessibility-in-DH#18]

**Comment by YuriDevAT** [comment]
Here are my findings of the two websites. I couldn't find how I can download it as a whole workbook in google sheets, that's why they are uploaded separately.

1. The first sheet is for the number of issues.
[DH Strukturen und Models - Issues of all websites.csv](https://github.com/YuriDevAT/accessibility-in-DH/files/11312129/DH.Strukturen.und.Models.-.Issues.of.all.websites.csv)

2. The second sheet is for the issue types and their occurrence.
[DH Strukturen und Models - Issue types and their occurance.csv](https://github.com/YuriDevAT/accessibility-in-DH/files/11312132/DH.Strukturen.und.Models.-.Issue.types.and.their.occurance.csv)

**Note:** For the second website I actually stopped after a few site. Each navigation link has several sub levels, and the issues seemed to be the same on every site.
_First website https://digital-humanities.at/en
Second website https://www.oeaw.ac.at/acdh/_

**Comment by lug-robin** [comment]
Thank you! I did it differently with one sheet (and its a pretty Excel sheet not CSV), but I can unify and put it all in one sheet! For now: 

[Testing Notes.xlsx](https://github.com/YuriDevAT/accessibility-in-DH/files/11346122/Testing.Notes.xlsx)

_First Website: adho: https://dh2023.adho.org/_
_Second Website:  http://www.dhwogem.org/_

Luckily the first one was pretty good with its issues and sadly the second one discontinued, but there we are!

**Comment by lug-robin** [comment]
It took me quite a while actually do unify it (there must have been an easier way), but there are the two files. I hope it's okay like that.

Number of issues: 
[DH.Strukturen.und.Models.-.Issues.of.all.websites.csv](https://github.com/YuriDevAT/accessibility-in-DH/files/11346895/DH.Strukturen.und.Models.-.Issues.of.all.websites.csv)
Type of occurances: 
[DH.Strukturen.und.Models.-.Issue.types.and.their.occurance.csv](https://github.com/YuriDevAT/accessibility-in-DH/files/11346899/DH.Strukturen.und.Models.-.Issue.types.and.their.occurance.csv)


I now have a headache and will go eat something.

**Comment by YuriDevAT** [comment]
Good work 🙌🏽  Hopefully, @EmiliaAnnaG is finishing her testing soon as well to make first viz.

Take enough break @lug-robin. I think we are good in time 👍🏽

**Comment by EmiliaAnnaG** [comment]
https://docs.google.com/spreadsheets/d/1ljcwWwzysWZI2JX0p9wboTaBP-xlFWWyQNO3mywquL8/edit?usp=sharing

Hier in Tabellenblatt 1 alle sammeln

**Comment by EmiliaAnnaG** [comment]
I added all of mine so the sheet should be complete
